---
- name: Build Hub and Spoke infrastructure with Bastion
  hosts: localhost
  any_errors_fatal: true
  gather_facts: false

  pre_tasks: 
    - name: generate new module ID if not defined 
      set_fact: 
        module_state_id: "{{ 999 | random }}"
      when: module_id == "" 

  vars:
    # Environment Variables for Terraform Backend (Storage Account)
    storage_access_key: "{{ lookup('env', 'ARM_ACCESS_KEY') | mandatory }}"
    storage_account_name: "{{ lookup('env', 'STORAGE_ACCOUNT_NAME') | mandatory }}"

    # Terraform Variables
    terraform_vars:
      subscription_id: "{{ subscription_id | mandatory }}"
      # location_east_us: "{{ location_east_us | default('East US') }}"
      location: "{{ location_west_us | default('West US') }}"
      admin_username: "{{ lookup('env', 'ADMIN_USER') | mandatory }}"
      admin_password: "{{ lookup('env', 'ADMIN_PASSWORD') | mandatory }}"
      tag_module_id: "{{ module_state_id | default(module_id) }}"
      tag_module_type: hubspo
      unique: "{{ unique | mandatory }}"

    azure_vars: 
      location: "{{ location_west_us | default('West US') }}"
      linux_fx_version: "PYTHON|3.12"
        # startup_command: "uvicorn chapp:app --host 0.0.0.0 --port 8080"


  tasks:
    - name: List all resource groups
      azure_rm_resourcegroup_info:
        auth_source: "auto"  # Automatically use `az login` credentials
      register: resource_groups

    # - debug:
    #     var: resource_groups
    - name: Fetch access key using Azure CLI
      command: >
        az storage account keys list
        --account-name {{ dev_core_storage_account }}
        --query [0].value
        -o tsv
      register: access_key_output

    - name: Set access key to variable
      set_fact:
        access_key: "{{ access_key_output.stdout }}"

    # - name: Debug access key
    #   debug:
    #     msg: "The access key is: {{ access_key }}"


    - name: Fetch subscription ID using Azure CLI
      command: >
        az account show --query id -o tsv
      register: subscription_id_output

    - name: Set subscription ID as a variable
      set_fact:
        subscription_id: "{{ subscription_id_output.stdout }}"

    - name: Set Terraform directory
      set_fact:
        terraform_dir: "../terraform/default/hub_and_spoke/"

    - name: Initialize and apply Terraform just vnet and bastion configuration
      community.general.terraform:
        project_path: "{{ terraform_dir }}"
        state: present
        force_init: false
        init_reconfigure: false
        variables: "{{ terraform_vars }}"
        backend_config:
          key: "{{ terraform_vars.tag_module_type + terraform_vars.tag_module_id + '.tfstate' }}"
          container_name: "state"
          storage_account_name: "{{ storage_account_name }}"
          access_key: "{{ storage_access_key }}"
      environment:
        ARM_SUBSCRIPTION_ID: "{{ subscription_id_output.stdout }}"
      register: tf_output

    - name: Output Terraform results
      debug:
        var: tf_output


    - name: Initialize and apply firewall terraform configuration
      community.general.terraform:
        project_path: "../terraform/default/firewall_and_route_tables" # "{{ terraform_dir }}"
        state: absent
        force_init: false
        init_reconfigure: false
        variables: "{{ terraform_vars }}"
        backend_config:
          key: "{{ terraform_vars.tag_module_type + terraform_vars.tag_module_id + '.tfstate' }}"
          container_name: "state"
          storage_account_name: "{{ storage_account_name }}"
          access_key: "{{ storage_access_key }}"
      environment:
        ARM_SUBSCRIPTION_ID: "{{ subscription_id_output.stdout }}"
      register: tf_output

    - name: Output Terraform results
      debug:
        var: tf_output

    - name: Extract Web App details from Terraform output
      set_fact:
        web_app_name: "{{ tf_output.outputs.web_app_name.value }}"
        web_app_resource_group_name: "{{ tf_output.outputs.resource_group_name.value }}"
        app_service_plan: "{{ tf_output.outputs.app_service_plan_name.value }}"

    - name: Package FastAPI app code
      archive:
        path: "../../lab/backend/"
        dest: "/tmp/fast_api_web_app.zip"
        format: zip

    - name: Package Original Lab Code 
      archive:
        path: "../../lab/smoke_test/backend/"
        dest: "/tmp/web_app.zip"
        format: zip

    - name: Set Python version and startup command in Web App
      shell: |
        az webapp config set --resource-group "{{ web_app_resource_group_name }}" --name "{{ web_app_name }}" --linux-fx-version "PYTHON|3.9"
      # environment:
      #   # az webapp config appsettings set --resource-group "{{ web_app_resource_group_name }}" --name "{{ web_app_name }}" --settings "STARTUP_COMMAND=uvicorn chapp:app --host 0.0.0.0 --port 8080"
      #   AZURE_CLIENT_ID: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
      #   AZURE_SECRET: "{{ lookup('env', 'AZURE_SECRET') }}"
      #   AZURE_TENANT: "{{ lookup('env', 'AZURE_TENANT') }}"
      #   AZURE_SUBSCRIPTION_ID: "{{ terraform_vars.subscription_id }}"
      args:
        executable: /bin/bash

    # - name: Ensure Web App exists
    #   azure.azcollection.azure_rm_webapp:
    #     resource_group: "{{ resource_group }}"
    #     name: "{{ web_app_name }}"
    #     plan: "{{ app_service_plan }}"
    #     location: "{{ azure_vars.location }}"
    #     state: present
    #     client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
    #     secret: "{{ lookup('env', 'AZURE_SECRET') }}"
    #     tenant: "{{ lookup('env', 'AZURE_TENANT') }}"
    #     subscription_id: "{{ terraform_vars.subscription_id }}"

    # - name: Set Web App configuration
    #   azure.azcollection.azure_rm_webappconfiguration:
    #     resource_group: "{{ resource_group }}"
    #     name: "{{ web_app_name }}"
    #     linux_fx_version: "{{ azure_vars.linux_fx_version }}"
    #     app_settings:
    #       STARTUP_COMMAND: ""
    #     client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
    #     secret: "{{ lookup('env', 'AZURE_SECRET') }}"
    #     tenant: "{{ lookup('env', 'AZURE_TENANT') }}"
    #     subscription_id: "{{ terraform_vars.subscription_id }}"

    - name: Deploy /tmp/web_app.zip to Azure Web App
      shell: |
        az webapp deploy --resource-group "{{ web_app_resource_group_name }}" --name "{{ web_app_name }}" --src-path "/tmp/web_app.zip" --type zip
      environment:
        AZURE_CLIENT_ID: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
        AZURE_SECRET: "{{ lookup('env', 'AZURE_SECRET') }}"
        AZURE_TENANT: "{{ lookup('env', 'AZURE_TENANT') }}"
        AZURE_SUBSCRIPTION_ID: "{{ terraform_vars.subscription_id }}"
      args:
        executable: /bin/bash
      register: deploy_output

    - name: Output deployment result
      debug:
        var: deploy_output.stdout